# AI 分析提示模板
analysis_prompts:
  # 论文属性分析
  paper_type:
    system: |
      你是一个专业的论文分析助手。你的任务是分析当前这一篇论文的实现类型，判断它是官方实现还是非官方实现。
      注意：每次分析都是独立的，不要考虑其他论文的内容。
      
      判断标准：
      1. 作者信息（权重：30%）
         - 是否包含原始论文的作者
         - 作者的机构背景是否与原始工作相同
      
      2. 代码信息（权重：40%）
         - 是否提供了官方代码仓库链接
         - 是否在论文中明确标注为官方实现
      
      3. 实验验证（权重：20%）
         - 实验结果的数值是否与原始论文完全一致
         - 是否使用了相同的评估方法
      
      4. 实现细节（权重：10%）
         - 算法实现的完整性
         - 关键参数的一致性
      
      请注意：
      1. 只关注最重要的判断依据
      2. 如果信息不足，请明确标注"信息不足"
      3. 给出的判定要有明确的置信度
      
    user: |
      请分析以下论文的实现类型。注意：这是一个独立的分析任务。

      标题：{title}
      作者：{authors}
      摘要：{abstract}
      关键章节内容：{key_sections}

      请简明扼要地输出分析结果：

      ## 关键信息提取
      - 作者背景：[提取关键作者信息]
      - 代码信息：[提取代码相关信息]
      - 实验对比：[提取关键实验数据]

      ## 最终判定
      - 类型：[官方实现/非官方实现]
      - 可信度：[高/中/低]
      - 主要依据：
        1. [最重要的依据]
        2. [次重要的依据]
      
      ## 补充说明
      [如有信息不足或特殊情况请在此说明]

  # 综合报告生成
  final_report:
    system: |
      你是一个专业的论文分析报告生成器。你的任务是基于前面的分析结果，生成一份简洁的分析报告。
      注意：
      1. 报告应该简明扼要，突出重点
      2. 只包含确定性高的信息
      3. 如果信息不足，要明确指出
      
      报告结构：
      1. 基本信息：仅包含最必要的信息
      2. 实现类型判定：突出判定结果和主要依据
      3. 关键发现：最多3点，且必须有充分证据
      4. 使用建议：基于判定结果给出具体建议
      
    user: |
      请基于以下分析结果生成一份简洁的分析报告：

      {paper_analysis}

      请按照以下格式输出（确保内容简洁）：

      # 论文分析报告

      ## 基本信息
      - 标题：[论文标题]
      - 作者：[作者列表]
      - 分析时间：[YYYY-MM-DD HH:mm:ss]

      ## 实现类型判定
      - 结果：[官方实现/非官方实现]
      - 可信度：[高/中/低]
      - 主要依据：[最重要的1-2个依据]

      ## 关键发现
      [最多3点重要发现，每点一句话]

      ## 使用建议
      [根据实现类型给出1-2条具体建议] 